openapi: 3.0.0
info:
  title: Quentry BFF API
  version: 1.0.0
  description: Backend for Frontend (BFF) API for Quentry authentication

servers:
  - url: http://localhost:3000
    description: Development server
  - url: /bff
    description: Production server

paths:
  /auth/login:
    post:
      summary: Authenticate with Keycloak
      description: Logs in to Keycloak and establishes a session
      operationId: keycloakLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Keycloak username
                password:
                  type: string
                  description: Keycloak password
              required:
                - username
                - password
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  user:
                    $ref: '#/components/schemas/User'
                  expiresIn:
                    type: number
                    description: Token expiration in seconds
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/logout:
    post:
      summary: Logout from Keycloak
      description: Ends the Keycloak session
      operationId: keycloakLogout
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string

  /quentry/login:
    post:
      summary: Authenticate with Quentry
      description: Uses existing Keycloak session to authenticate with Quentry
      operationId: quentryLogin
      security:
        - keycloakAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Quentry username
                password:
                  type: string
                  description: Quentry password
              required:
                - username
                - password
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  user:
                    $ref: '#/components/schemas/QuentryUser'
                  urlsLookup:
                    type: object
                    additionalProperties:
                      type: string
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /quentry/logout:
    post:
      summary: Logout from Quentry
      description: Ends the Quentry session but keeps Keycloak session
      operationId: quentryLogout
      security:
        - keycloakAuth: []
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string

  /quentry/status:
    get:
      summary: Get Quentry session status
      description: Check if the user is authenticated with Quentry
      operationId: quentryStatus
      security:
        - keycloakAuth: []
      responses:
        '200':
          description: Status retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  authenticated:
                    type: boolean
                  expiresIn:
                    type: number
                    description: Seconds until session expires
                  user:
                    $ref: '#/components/schemas/QuentryUser'

  /quentry/api/{path}:
    get:
      summary: Proxy to Quentry API
      description: Forwards requests to Quentry API with authentication
      operationId: quentryApiProxy
      security:
        - keycloakAuth: []
        - quentryAuth: []
      parameters:
        - in: path
          name: path
          required: true
          schema:
            type: string
          description: API path to forward to Quentry
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: User ID
        username:
          type: string
        email:
          type: string
        name:
          type: string
        roles:
          type: array
          items:
            type: string

    QuentryUser:
      type: object
      properties:
        username:
          type: string
        fullName:
          type: string
        email:
          type: string
        id:
          type: string
          description: User system ID

    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        status:
          type: integer

  securitySchemes:
    keycloakAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Keycloak JWT token
    quentryAuth:
      type: apiKey
      in: cookie
      name: quentry_session
      description: Quentry session cookie
